name: Check PullRequest

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      
      - name: Setup PR workflow
        run: |
          echo a > files-sha1.txt
          echo "$CL" > src/config-local.js
        env:
          CL: |
            module.exports = {
              run_build: true,
              verbose: { cp: true, command: true },
              deploy: { enable: false },
              check_update_to_date: false,
            }

      - name: Build VuePress
        run: node src/main.js
